import type { Iso3 } from '../../src/lib/data/types.js';

/**
 * Capitales en français. La source ne fournit que l'anglais : toute capitale
 * absente de cette table est réputée s'écrire à l'identique dans les deux
 * langues (Berlin, Madrid, Nairobi…). Relue à la main, pays par pays.
 */
export const CAPITAL_FR_OVERRIDES: Readonly<Record<Iso3, string>> = {
  AFG: 'Kaboul',
  AND: 'Andorre-la-Vieille',
  ARE: 'Abou Dabi',
  ARM: 'Erevan',
  AUT: 'Vienne',
  AZE: 'Bakou',
  BEL: 'Bruxelles',
  BRA: 'Brasilia',
  BTN: 'Thimphou',
  CHE: 'Berne',
  CHN: 'Pékin',
  COL: 'Bogota',
  CUB: 'La Havane',
  CYP: 'Nicosie',
  DNK: 'Copenhague',
  DZA: 'Alger',
  EGY: 'Le Caire',
  ESH: 'Laâyoune',
  ETH: 'Addis-Abeba',
  GBR: 'Londres',
  GEO: 'Tbilissi',
  GRC: 'Athènes',
  GRD: 'Saint-Georges',
  GTM: 'Guatemala',
  IRN: 'Téhéran',
  IRQ: 'Bagdad',
  ISR: 'Jérusalem',
  KGZ: 'Bichkek',
  KIR: 'Tarawa-Sud',
  KOR: 'Séoul',
  KWT: 'Koweït',
  LBN: 'Beyrouth',
  MDA: 'Chisinau',
  MEX: 'Mexico',
  MLT: 'La Valette',
  MNG: 'Oulan-Bator',
  NPL: 'Katmandou',
  OMN: 'Mascate',
  PAN: 'Panama',
  PHL: 'Manille',
  POL: 'Varsovie',
  PRT: 'Lisbonne',
  PRY: 'Asuncion',
  ROU: 'Bucarest',
  RUS: 'Moscou',
  SAU: 'Riyad',
  SGP: 'Singapour',
  SMR: 'Saint-Marin',
  SOM: 'Mogadiscio',
  SYR: 'Damas',
  TCD: "N'Djaména",
  TJK: 'Douchanbé',
  TKM: 'Achgabat',
  TTO: "Port-d'Espagne",
  USA: 'Washington',
  UZB: 'Tachkent',
  VAT: 'Cité du Vatican',
  VNM: 'Hanoï',
  YEM: 'Sanaa',
  DOM: 'Saint-Domingue',
};
