/**
 * Noms de monnaies en français, par code ISO 4217.
 * La source ne fournit que l'anglais : cette table est écrite et relue à la main.
 * Le script échoue si une monnaie utilisée par un pays du jeu manque ici.
 */
export const CURRENCY_FR: Readonly<Record<string, string>> = {
  AED: 'dirham des Émirats arabes unis',
  AFN: 'afghani afghan',
  ALL: 'lek albanais',
  AMD: 'dram arménien',
  ANG: 'florin antillais',
  AOA: 'kwanza angolais',
  ARS: 'peso argentin',
  AUD: 'dollar australien',
  AWG: 'florin arubais',
  AZN: 'manat azerbaïdjanais',
  BAM: 'mark convertible de Bosnie-Herzégovine',
  BBD: 'dollar barbadien',
  BDT: 'taka bangladais',
  BHD: 'dinar bahreïni',
  BIF: 'franc burundais',
  BMD: 'dollar bermudien',
  BND: 'dollar de Brunei',
  BOB: 'boliviano bolivien',
  BRL: 'real brésilien',
  BSD: 'dollar bahaméen',
  BTN: 'ngultrum bhoutanais',
  BWP: 'pula botswanais',
  BYN: 'rouble biélorusse',
  BZD: 'dollar bélizien',
  CAD: 'dollar canadien',
  CDF: 'franc congolais',
  CHF: 'franc suisse',
  CKD: 'dollar des îles Cook',
  CLP: 'peso chilien',
  CNY: 'yuan chinois',
  COP: 'peso colombien',
  CRC: 'colón costaricien',
  CUC: 'peso convertible cubain',
  CUP: 'peso cubain',
  CVE: 'escudo cap-verdien',
  CZK: 'couronne tchèque',
  DJF: 'franc djiboutien',
  DKK: 'couronne danoise',
  DOP: 'peso dominicain',
  DZD: 'dinar algérien',
  EGP: 'livre égyptienne',
  ERN: 'nakfa érythréen',
  ETB: 'birr éthiopien',
  EUR: 'euro',
  FJD: 'dollar fidjien',
  FKP: 'livre des Malouines',
  FOK: 'couronne féroïenne',
  GBP: 'livre sterling',
  GEL: 'lari géorgien',
  GGP: 'livre de Guernesey',
  GHS: 'cedi ghanéen',
  GIP: 'livre de Gibraltar',
  GMD: 'dalasi gambien',
  GNF: 'franc guinéen',
  GTQ: 'quetzal guatémaltèque',
  GYD: 'dollar guyanien',
  HKD: 'dollar de Hong Kong',
  HNL: 'lempira hondurien',
  HTG: 'gourde haïtienne',
  HUF: 'forint hongrois',
  IDR: 'roupie indonésienne',
  ILS: 'nouveau shekel israélien',
  IMP: 'livre mannoise',
  INR: 'roupie indienne',
  IQD: 'dinar irakien',
  IRR: 'rial iranien',
  ISK: 'couronne islandaise',
  JEP: 'livre de Jersey',
  JMD: 'dollar jamaïcain',
  JOD: 'dinar jordanien',
  JPY: 'yen japonais',
  KES: 'shilling kényan',
  KGS: 'som kirghize',
  KHR: 'riel cambodgien',
  KID: 'dollar de Kiribati',
  KMF: 'franc comorien',
  KPW: 'won nord-coréen',
  KRW: 'won sud-coréen',
  KWD: 'dinar koweïtien',
  KYD: 'dollar des îles Caïmans',
  KZT: 'tenge kazakh',
  LAK: 'kip laotien',
  LBP: 'livre libanaise',
  LKR: 'roupie srilankaise',
  LRD: 'dollar libérien',
  LSL: 'loti lesothan',
  LYD: 'dinar libyen',
  MAD: 'dirham marocain',
  MDL: 'leu moldave',
  MGA: 'ariary malgache',
  MKD: 'denar macédonien',
  MMK: 'kyat birman',
  MNT: 'tugrik mongol',
  MOP: 'pataca macanaise',
  MRU: 'ouguiya mauritanien',
  MUR: 'roupie mauricienne',
  MVR: 'rufiyaa maldivienne',
  MWK: 'kwacha malawien',
  MXN: 'peso mexicain',
  MYR: 'ringgit malaisien',
  MZN: 'metical mozambicain',
  NAD: 'dollar namibien',
  NGN: 'naira nigérian',
  NIO: 'córdoba nicaraguayen',
  NOK: 'couronne norvégienne',
  NPR: 'roupie népalaise',
  NZD: 'dollar néo-zélandais',
  OMR: 'rial omanais',
  PAB: 'balboa panaméen',
  PEN: 'sol péruvien',
  PGK: 'kina papouan',
  PHP: 'peso philippin',
  PKR: 'roupie pakistanaise',
  PLN: 'zloty polonais',
  PYG: 'guaraní paraguayen',
  QAR: 'riyal qatari',
  RON: 'leu roumain',
  RSD: 'dinar serbe',
  RUB: 'rouble russe',
  RWF: 'franc rwandais',
  SAR: 'riyal saoudien',
  SBD: 'dollar des îles Salomon',
  SCR: 'roupie seychelloise',
  SDG: 'livre soudanaise',
  SEK: 'couronne suédoise',
  SGD: 'dollar de Singapour',
  SHP: 'livre de Sainte-Hélène',
  SLE: 'leone sierra-léonais',
  SOS: 'shilling somalien',
  SRD: 'dollar surinamais',
  SSP: 'livre sud-soudanaise',
  STN: 'dobra santoméen',
  SYP: 'livre syrienne',
  SZL: 'lilangeni swazi',
  THB: 'baht thaïlandais',
  TJS: 'somoni tadjik',
  TMT: 'manat turkmène',
  TND: 'dinar tunisien',
  TOP: "pa'anga tongien",
  TRY: 'livre turque',
  TTD: 'dollar de Trinité-et-Tobago',
  TVD: 'dollar tuvaluan',
  TWD: 'nouveau dollar taïwanais',
  TZS: 'shilling tanzanien',
  UAH: 'hryvnia ukrainienne',
  UGX: 'shilling ougandais',
  USD: 'dollar américain',
  UYU: 'peso uruguayen',
  UZS: 'sum ouzbek',
  VES: 'bolívar vénézuélien',
  VND: 'dong vietnamien',
  VUV: 'vatu vanuatuan',
  WST: 'tala samoan',
  XAF: 'franc CFA (BEAC)',
  XCD: 'dollar des Caraïbes orientales',
  XOF: 'franc CFA (BCEAO)',
  XPF: 'franc pacifique',
  YER: 'rial yéménite',
  ZAR: 'rand sud-africain',
  ZMW: 'kwacha zambien',
  ZWB: 'dollar zimbabwéen',
  ZWG: 'ZiG zimbabwéen',
};

/**
 * Monnaies fausses ou périmées à la source, corrigées à la main.
 *
 * Le Zimbabwe y traîne encore les neuf devises du régime multi-devises de
 * 2009-2019 (dont le yen et l'euro), abandonné depuis. Le pays émet le ZiG
 * (Zimbabwe Gold, code ISO 4217 ZWG) depuis avril 2024.
 *
 * Cuba y garde le peso convertible, supprimé en 2021.
 */
export const CURRENCY_OVERRIDES: Readonly<
  Record<string, readonly { code: string; name: string; symbol: string | null }[]>
> = {
  ZWE: [{ code: 'ZWG', name: 'Zimbabwe Gold', symbol: 'ZiG' }],
  CUB: [{ code: 'CUP', name: 'Cuban peso', symbol: '$' }],
};

/** La source donne quelques noms anglais tronqués ou en minuscule. */
export const CURRENCY_EN_OVERRIDES: Readonly<Record<string, string>> = {
  DKK: 'Danish krone',
  GEL: 'Georgian lari',
  GMD: 'Gambian dalasi',
  MKD: 'Macedonian denar',
  NOK: 'Norwegian krone',
  ZWB: 'Zimbabwean dollar',
};

/**
 * Genre du nom générique de chaque monnaie, pour composer « **le** sol
 * péruvien », « **la** livre sterling », « **l'**euro ». On n'a besoin que du
 * premier mot : le reste est un adjectif qui s'accorde déjà dans la table
 * ci-dessus. Le build échoue si un mot générique manque ici.
 */
export const CURRENCY_GENDER: Readonly<Record<string, 'm' | 'f'>> = {
  afghani: 'm', ariary: 'm', baht: 'm', balboa: 'm', birr: 'm', boliviano: 'm',
  bolívar: 'm', cedi: 'm', colón: 'm', couronne: 'f', córdoba: 'm',
  dalasi: 'm', denar: 'm', dinar: 'm', dirham: 'm', dobra: 'm', dollar: 'm',
  dong: 'm', dram: 'm', escudo: 'm', euro: 'm', forint: 'm', franc: 'm',
  gourde: 'f', guaraní: 'm', hryvnia: 'f', kina: 'm', kip: 'm', kwacha: 'm',
  kwanza: 'm', kyat: 'm', lari: 'm', lek: 'm', lempira: 'm', leone: 'm',
  leu: 'm', lilangeni: 'm', livre: 'f', loti: 'm', manat: 'm', mark: 'm',
  metical: 'm', naira: 'm', nakfa: 'm', ngultrum: 'm', nouveau: 'm',
  ouguiya: 'm', 'pa’anga': 'm', peso: 'm', pula: 'm', quetzal: 'm', rand: 'm',
  real: 'm', rial: 'm', riel: 'm', ringgit: 'm', riyal: 'm', rouble: 'm',
  roupie: 'f', rufiyaa: 'f', shilling: 'm', sol: 'm', som: 'm', somoni: 'm',
  sum: 'm', taka: 'm', tala: 'm', tenge: 'm', tugrik: 'm', vatu: 'm',
  won: 'm', yen: 'm', yuan: 'm', zloty: 'm', ZiG: 'm',
};
